# Generated by Django 5.2.1 on 2025-06-28 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_drone_store_delivery_dronetelemetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartDropPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartdrop_points', to='inventory.retailer')),
            ],
        ),
    ]
