# Generated by Django 5.2.1 on 2025-06-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_deliveryperson_delivery_mode_accidentevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='suggested_mode',
            field=models.CharField(choices=[('drone', 'Drone'), ('biker', 'Biker')], default='biker', max_length=20),
        ),
    ]
