# Generated by Django 5.2.1 on 2025-06-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_delivery_suggested_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='mimic_accident',
            field=models.BooleanField(default=False),
        ),
    ]
