# Generated by Django 5.2.1 on 2025-07-06 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_deliveryperson_accident_flag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('code', models.CharField(blank=True, max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('tampered', models.BooleanField(default=False)),
                ('info', models.CharField(blank=True, max_length=200)),
                ('scan_time', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parcel_photos/')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='inventory.truck')),
            ],
        ),
    ]
