# Generated by Django 5.2.1 on 2025-07-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_truck_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='truck_photos/'),
        ),
    ]
